name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  METARANK_TRACKING: false

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - jvm: 11
            platform: ubuntu-22.04
            architecture: x64
          - jvm: 21
            platform: ubuntu-22.04
            architecture: x64
          - jvm: 11
            platform: macos-12
            architecture: x64
          - jvm: 11
            platform: macos-14
            architecture: aarch64
          - jvm: 11
            platform: windows-2022
            architecture: x64

    steps:
    - name: install libomp
      run: brew install libomp && sudo mkdir -p /usr/local/lib/ && sudo ln -s /opt/homebrew/opt/libomp/lib/libomp.dylib /usr/local/lib/libomp.dylib
      if: runner.os == 'macOS'

    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - name: Set FBCDN ubuntu mirror for archive
      run: "sudo sed -i -e 's/azure.archive.ubuntu.com/mirror.facebook.net/g' /etc/apt/sources.list"
      if: runner.os == 'Linux'

    - name: cat sources.list
      run: "sudo cat /etc/apt/sources.list"
      if: runner.os == 'Linux'

    - name: Start Redis on Linux
      run: sudo apt-get update && sudo apt-get install redis-server haveged
      if: runner.os == 'Linux'

    - name: Start Redis on Mac
      run: brew install redis sbt && brew services start redis
      if: runner.os == 'macOS'

    - name: Start Redis on Windows
      run: choco install memurai-developer
      if: runner.os == 'Windows'

    - name: start haveged
      run: docker run --privileged -d hortonworks/haveged:1.1.0
      if: runner.os == 'Linux'

    - name: check enthropy
      run: cat /proc/sys/kernel/random/entropy_avail && sudo dmesg
      if: runner.os == 'Linux'

    - uses: actions/cache@v4
      with:
        path: ~/.sbt ~/.m2 ~/.ivy2 ~/.cache
        key: ${{ runner.os }}-build-${{ hashFiles('build.sbt', 'api/build.sbt', 'ingest/build.sbt', 'core/build.sbt', 'project/Deps.scala') }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jvm }}
        architecture: ${{ matrix.architecture }}
        distribution: 'temurin'

    - name: Run tests
      run: sbt -mem 3000 test
